language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: imU+od2Qy3Fd4+omceQ7jeErLRPfvGP25A/wq7iVM/Q9mE+G+hFrZt8k97/BeFpUHtNA7ReY4FJRDMTQQPABH/3HINaVeXPdhvcxKVPURjN9Wb76tvTymThTB+B+R3g1ClEbTXsl3mNIqmJSdbpu4aJwhDMQEg8yVqNRmCM4PS3ZTIyVxRIeTgepDm28VFpCTvQ53DBIzAuPEDqTokj6nwlkfdkVWkALJXW9y0fZ7Foj6E7vu7jnrgUMf4Pfv//wZEn63cbzErKf2h0MgoUIYv3Vjk/vvtRoNUMbpW9v3R2F0GhnL8i5S1Cnh98w6dYxEa3e7IjEls23K3/2ulgWYzu9NAI12xySkQtryycY0KKH+dKr/aarPBAefZRlUNNHvWVtjWR/KGEKITKEAavEWwh5+mWP3f2H1zlWxXBqRLpgEgh0XBAfBK1KKqWWDcwxpcsUNVuxPP61cYwv/5VwVNrhv6Jd+lc/vFjSrSzLF8Nvmr5tTXEjmBrKpBeTMgE0bCUa8CpY/7MEJD46OMLQDOJI13m2VUJLG5avNGHmc29rj5B0r0jXvTzz5PjAH41llLWdmXqm3ibbxwyxy4KajGE7adS1+5d4gC1Nnjr2dzCtInkNgXi3FqjQPeiRBuLSXQnW00V8rKplDAlpgRVd+T0WADfeiBrx9Q/uGJpmdi4=
  app: guarded-ravine-41063
